In [88]:
import pandas as pd

In [89]:
# FIPS 10-4 to Country Name mapping
fips_to_country = {
    'AA': 'Aruba',
    'AC': 'Antigua and Barbuda',
    'AD': 'Akrotiri',
    'AE': 'United Arab Emirates',
    'AF': 'Afghanistan',
    'AG': 'Algeria',
    'AJ': 'Azerbaijan',
    'AL': 'Albania',
    'AM': 'Armenia',
    'AN': 'Andorra',
    'AO': 'Angola',
    'AQ': 'American Samoa',
    'AR': 'Argentina',
    'AS': 'Australia',
    'AT': 'Ashmore and Cartier Islands',
    'AU': 'Austria',
    'AV': 'Anguilla',
    'AY': 'Antarctica',
    'BA': 'Bahrain',
    'BB': 'Barbados',
    'BC': 'Botswana',
    'BD': 'Bermuda',
    'BE': 'Belgium',
    'BF': 'Bahamas',
    'BG': 'Bangladesh',
    'BH': 'Belize',
    'BK': 'Bosnia and Herzegovina',
    'BL': 'Bolivia',
    'BM': 'Myanmar',
    'BN': 'Benin',
    'BO': 'Belarus',
    'BP': 'Solomon Islands',
    'BQ': 'Navassa Island',
    'BR': 'Brazil',
    'BT': 'Bhutan',
    'BU': 'Bulgaria',
    'BV': 'Bouvet Island',
    'BX': 'Brunei',
    'BY': 'Burundi',
    'CA': 'Canada',
    'CB': 'Cambodia',
    'CD': 'Chad',
    'CE': 'Sri Lanka',
    'CF': 'Republic of the Congo',
    'CG': 'Democratic Republic of the Congo',
    'CH': 'China',
    'CI': 'Cile',
    'CJ': 'Cayman Islands',
    'CK': 'Cocos (Keeling) Islands',
    'CM': 'Cameroon',
    'CN': 'Comoros',
    'CO': 'Colombia',
    'CQ': 'Northern Mariana Islands',
    'CR': 'Coral Sea Islands',
    'CS': 'Costa Rica',
    'CT': 'Central African Republic',
    'CU': 'Cuba',
    'CV': 'Cape Verde',
    'CW': 'Cook Islands',
    'CY': 'Cyprus',
    'DA': 'Denmark',
    'DJ': 'Djibouti',
    'DO': 'Dominica',
    'DR': 'Dominican Republic',
    'EC': 'Ecuador',
    'EE': 'European Union',
    'EG': 'Egypt',
    'EI': 'Ireland',
    'EK': 'Equatorial Guinea',
    'EN': 'Estonia',
    'ER': 'Eritrea',
    'ES': 'El Salvador',
    'ET': 'Ethiopia',
    'EU': 'Europa Island',
    'EZ': 'Czechia',
    'FG': 'French Guiana',
    'FI': 'Finland',
    'FJ': 'Fiji',
    'FK': 'Falkland Islands',
    'FM': 'Micronesia',
    'FO': 'Faroe Islands',
    'FP': 'French Polynesia',
    'FR': 'France',
    'FS': 'French Southern and Antarctic Lands',
    'GA': 'Gambia',
    'GB': 'Gabon',
    'GG': 'Georgia',
    'GH': 'Ghana',
    'GI': 'Gibraltar',
    'GJ': 'Grenada',
    'GK': 'Guernsey',
    'GL': 'Greenland',
    'GM': 'Germany',
    'GO': 'Glorioso Islands',
    'GP': 'Guadeloupe',
    'GQ': 'Guam',
    'GR': 'Greece',
    'GT': 'Guatemala',
    'GV': 'Guinea',
    'GY': 'Guyana',
    'GZ': 'Palestine',
    'HA': 'Haiti',
    'HK': 'Hong Kong',
    'HM': 'Heard Island and McDonald Islands',
    'HO': 'Honduras',
    'HR': 'Croatia',
    'HU': 'Hungary',
    'IC': 'Iceland',
    'ID': 'Indonesia',
    'IM': 'Isle of Man',
    'IN': 'India',
    'IO': 'British Indian Ocean Territory',
    'IP': 'Clipperton Island',
    'IR': 'Iran',
    'IS': 'Israel',
    'IT': 'Italy',
    'IV': 'Côte d’Ivoire',
    'IZ': 'Iraq',
    'JA': 'Japan',
    'JE': 'Jersey',
    'JM': 'Jamaica',
    'JN': 'Jan Mayen',
    'JO': 'Jordan',
    'JU': 'Juan de Nova Island',
    'KE': 'Kenya',
    'KG': 'Kyrgyzstan',
    'KN': 'North Korea',
    'KR': 'Kiribati',
    'KS': 'South Korea',
    'KT': 'Christmas Island',
    'KU': 'Kuwait',
    'KV': 'Kosovo',
    'KZ': 'Kazakhstan',
    'LA': 'Laos',
    'LE': 'Lebanon',
    'LG': 'Latvia',
    'LH': 'Lithuania',
    'LI': 'Liberia',
    'LO': 'Slovakia',
    'LS': 'Lichtenstein',
    'LT': 'Lesotho',
    'LU': 'Luxembourg',
    'LY': 'Libya',
    'MA': 'Madagascar',
    'MB': 'Martinique',
    'MC': 'Macau',
    'MD': 'Moldova',
    'MF': 'Mayotte',
    'MG': 'Mongolia',
    'MH': 'Montserrat',
    'MI': 'Malawi',
    'MJ': 'Montenegro',
    'MK': 'North Macedonia',
    'ML': 'Mali',
    'MN': 'Monaco',
    'MO': 'Morocco',
    'MP': 'Mauritius',
    'MR': 'Mauritania',
    'MT': 'Malta',
    'MU': 'Oman',
    'MV': 'Maldives',
    'MX': 'Mexico',
    'MY': 'Malaysia',
    'MW': 'Montenegro',
    'MZ': 'Mozambique',
    'NC': 'New Caledonia',
    'NE': 'Niue',
    'NF': 'Norfolk Island',
    'NG': 'Niger',
    'NH': 'Vanuatu',
    'NI': 'Nigeria',
    'NL': 'Netherlands',
    'NN': 'Sint Maarten',
    'NO': 'Norway',
    'NP': 'Nepal',
    'NR': 'Nauru',
    'NS': 'Suriname',
    'NT': 'Netherlands Antilles',
    'NU': 'Nicaragua',
    'NZ': 'New Zealand',
    'OD': 'South Sudan',
    'PA': 'Paraguay',
    'PC': 'Pitcairn Islands',
    'PE': 'Peru',
    'PF': 'Paracel Islands',
    'PG': 'Spratly Islands',
    'PJ': 'Etorofu, Habomai, Shikotan, Kunashiri Islands',
    'PK': 'Pakistan',
    'PL': 'Poland',
    'PM': 'Panama',
    'PO': 'Portugal',
    'PP': 'Papua New Guinea',
    'PS': 'Palau',
    'PU': 'Guinnea-Bissau',
    'QA': 'Qatar',
    'RE': 'Réunion',
    'RI': 'Serbia',
    'RM': 'Marshall Islands',
    'RN': 'Saint Martin',
    'RO': 'Romania',
    'RP': 'Philippines',
    'RQ': 'Puerto Rico',
    'RS': 'Russia',
    'RW': 'Rwanda',
    'SA': 'Saudi Arabia',
    'SB': 'Saint Pierre and Miquelon',
    'SC': 'Saint Kitts and Nevis',
    'SE': 'Seychelles',
    'SF': 'South Africa',
    'SG': 'Singapore',
    'SH': 'Saint Helena, Ascension, and Tristan da Cunha',
    'SI': 'Slovenia',
    'SL': 'Sierra Leone',
    'SM': 'San Marino',
    'SN': 'Singapore',
    'SO': 'Somalia',
    'SP': 'Spain',
    'SR': 'Suriname',
    'ST': 'Saint Lucia',
    'SU': 'Sudan',
    'SV': 'Svalbard',
    'SW': 'Sweden',
    'SX': 'South Georgia and the South Sandwich Islands',
    'SY': 'Syria',
    'SZ': 'Switzerland',
    'TB': 'Saint Barthelemy',
    'TD': 'Trinidad and Tobago',
    'TE': 'Tromelin Island',
    'TH': 'Thailand',
    'TI': 'Tajikistan',
    'TK': 'Turks and Caicos Islands',
    'TL': 'Tokelau',
    'TN': 'Tonga',
    'TO': 'Togo',
    'TP': 'Sao Tome and Principe',
    'TS': 'Tunisia',
    'TT': 'Timor-Leste',
    'TU': 'Turkey',
    'TV': 'Tuvalu',
    'TW': 'Taiwan',
    'TX': 'Turkmenistan',
    'TZ': 'Tanzania',
    'UC': 'Curacao',
    'UG': 'Uganda',
    'UK': 'United Kingdom',
    'UM': 'U.S. Minor Outlying Islands',
    'UP': 'Ukraine',
    'US': 'United States',
    'UV': 'Burkina Faso',
    'UY': 'Uruguay',
    'UZ': 'Uzbekistan',
    'VC': 'Saint Vincent and the Grenadines',
    'VE': 'Venezuela',
    'VI': 'British Virgin Islands',
    'VM': 'Vietnam',
    'VQ': 'U.S. Virgin Islands',
    'VT': 'Vatican City',
    'WA': 'Namibia',
    'WE': 'Palestine',
    'WF': 'Wallis and Futuna',
    'WI': 'Western Sahara',
    'WQ': 'Wake Island',
    'WS': 'Samoa',
    'WZ': 'Eswatini',
    'YM': 'Yemen',
    'ZA': 'Zambia',
    'ZI': 'Zimbabwe',
}

# FIPS Extension for some missing codes
fips_extension = {
    'OC': 'Oceania',
    'OS': 'Oceans',
    'RB': 'Serbia',
    'YI': 'Serbia',
    'HQ': 'Howland Island',
    'KQ': 'Kingman Reef',
    'JQ': 'Johnston Atoll',
    'DQ': 'Jarvis Island',
    'LQ': 'Palmyra Atoll',  
}

fips = {**fips_to_country, **fips_extension}

In [90]:
# Function to convert 2-letter country codes to country names
def code_to_country(code):
    try:
        country = fips[code]
        return country
    except:
        raise ValueError(f"Invalid country code: {code}")

In [91]:
# Load the mentions dataset from data/GDELT/weekly_media_attention_query_class34_better_disambiguation.csv
path_mentions = "../data/GDELT/weekly_media_attention_query_class34_better_disambiguation.csv"
df_mentions = pd.read_csv(path_mentions)

# Display the first few rows of the dataframe
df_mentions.head()

,mention_week,conflict_country,media_country,mentions_count,distinct_events,verbal_conflict_mentions,material_conflict_mentions,verbal_conflict_unique_events,material_conflict_unique_events,state_mentions,...,civilians_unique_events,international_mentions,international_unique_events,avg_tone,stddev_tone,median_tone,avg_impact,stddev_impact,median_impact,top_article_url
0,2025-09-15,ZA,Turkey,7,6,7,0,6,0,6,...,0,0,0,-8.289937,8.459146,-1.510574,-2.0,0.0,-2.0,http://www.haberler.com/guncel/zambiya-da-cumh...
1,2018-12-24,AS,China,6,6,6,0,6,0,2,...,0,0,0,-1.016659,8.419795,-6.451613,-2.0,0.0,-2.0,http://www.xinhuanet.com/english/2018-12/27/c_...
2,2024-02-12,GM,Nigeria,7,6,7,0,6,0,5,...,1,0,0,-1.940944,8.176807,-8.244994,-2.0,0.0,-2.0,https://www.theaustralian.com.au/news/latest-n...
3,2016-09-19,SU,Pakistan,6,3,6,0,3,0,4,...,0,0,0,1.247945,8.041191,5.994550,-2.0,0.0,-2.0,http://www.dnd.com.pk/president-mamnoon-for-bo...
4,2021-04-26,SG,Ukraine,6,6,6,0,6,0,6,...,0,0,0,2.202823,7.826655,6.569343,-2.0,0.0,-2.0,https://nv.ua/opinion/ukraina-rossiya-kak-priv...

In [92]:
# Load the fatalities dataset from data/ACLED/number_of_reported_fatalities_by_country-year_as-of-12Dec2025.csv
path_fatalities = "../data/ACLED/number_of_reported_fatalities_by_country-year_as-of-12Dec2025.csv"
df_fatalities = pd.read_csv(path_fatalities, encoding='utf-8', sep=';')

# Display the first few rows of the dataframe
df_fatalities.head()

       COUNTRY  YEAR  FATALITIES
0  Afghanistan  2017       36360
1  Afghanistan  2018       42991
2  Afghanistan  2019       41419
3  Afghanistan  2020       30977
4  Afghanistan  2021       42425

In [93]:
# Create a new dataset with country name, number of mentions in 2025, and number of fatalities in 2025

# First, add column YEAR (column 'mention_week' contains the year at the start)
df_mentions_year = df_mentions.copy()
df_mentions_year['year'] = df_mentions_year['mention_week'].str[:4].astype(int)
# Remove lines with country codes not in pcountries
df_mentions_year = df_mentions_year[df_mentions_year['conflict_country'].isin(set(fips_to_country.keys()))]
# Aggregate the number of mentions by country and year
mentions_agg = df_mentions_year.groupby(['conflict_country', 'year'])['mentions_count'].sum().reset_index()
# Rename columns for clarity
mentions_agg.columns = ['COUNTRY', 'YEAR', 'MENTIONS']
# Map country codes to country names
mentions_agg['COUNTRY'] = mentions_agg['COUNTRY'].apply(code_to_country)
# If a country appears multiple times, sum the mentions
mentions_agg = mentions_agg.groupby(['COUNTRY', 'YEAR'])['MENTIONS'].sum().reset_index()

# Select relevant columns
fatalities_agg = df_fatalities[['COUNTRY', 'YEAR', 'FATALITIES']]
# Merge the two datasets on country name
merged_df = pd.merge(mentions_agg, fatalities_agg, on=['COUNTRY', 'YEAR'], how='inner')
# Display the merged dataframe
merged_df.head()

       COUNTRY  YEAR  MENTIONS  FATALITIES
0  Afghanistan  2017   1072037       36360
1  Afghanistan  2018    969765       42991
2  Afghanistan  2019    608526       41419
3  Afghanistan  2020    414241       30977
4  Afghanistan  2021    991360       42425

In [94]:
# Show highest values of mentions and fatalities
print("Top 10 countries by mentions in 2025:")
print(merged_df.sort_values(by='MENTIONS', ascending=False).head(10))
print()

print("Top 10 countries by fatalities in 2025:")
print(merged_df.sort_values(by='FATALITIES', ascending=False).head(10))
print()

print("Bottom 10 countries by mentions in 2025:")
print(merged_df.sort_values(by='MENTIONS', ascending=True).head(10))
print()

print("Bottom 10 countries by fatalities in 2025:")
print(merged_df.sort_values(by='FATALITIES', ascending=True).head(10))

Top 10 countries by mentions in 2025:
            COUNTRY  YEAR  MENTIONS  FATALITIES
1580  United States  2020  16420759          74
1581  United States  2021  13276880          87
1583  United States  2023  12520477          66
1584  United States  2024  12062253          33
1585  United States  2025  11110004          50
1582  United States  2022   9899459          98
726          Israel  2024   7107152          99
725          Israel  2023   5774152        1772
1247         Russia  2022   5332775          97
720          Israel  2018   4452622           7

Top 10 countries by fatalities in 2025:
          COUNTRY  YEAR  MENTIONS  FATALITIES
1563      Ukraine  2024   2214029       73570
1564      Ukraine  2025   1927656       73018
698          Iraq  2016   2037193       56032
1444        Syria  2017   2931065       54122
1     Afghanistan  2018    969765       42991
4     Afghanistan  2021    991360       42425
2     Afghanistan  2019    608526       41419
1561      Ukraine  2022   4170213       40573
1562      Ukraine  2023   2876916       39762
0     Afghanistan  2017   1072037       36360

Bottom 10 countries by mentions in 2025:
                        COUNTRY  YEAR  MENTIONS  FATALITIES
1630          Wallis and Futuna  2021         6           0
1502                    Tokelau  2021         7           0
1276  Saint Pierre and Miquelon  2024         8           0
488            Falkland Islands  2019        14           0
1275  Saint Pierre and Miquelon  2021        15           0
1110                       Niue  2021        21           0
1111             Norfolk Island  2021        27           0
490            Falkland Islands  2021        40           0
1129   Northern Mariana Islands  2025        41           0
716                 Isle of Man  2024        48           0

Bottom 10 countries by fatalities in 2025:
                       COUNTRY  YEAR  MENTIONS  FATALITIES
1125           North Macedonia  2023     35770           0
1126           North Macedonia  2024     39011           0
1127           North Macedonia  2025     29169           0
1128  Northern Mariana Islands  2024      1972           0
1129  Northern Mariana Islands  2025        41           0
1131                    Norway  2021     68597           0
1133                    Norway  2023     66730           0
1134                    Norway  2024     71943           0
1626                   Vietnam  2022     46149           0
1121           North Macedonia  2019     81309           0

In [95]:
# Save the merged dataset to a new CSV file
output_path = "../data/processed/scatter_plot.csv"
merged_df.to_csv(output_path, index=False)
print(f"Merged dataset saved to {output_path}")

Merged dataset saved to ../data/processed/scatter_plot.csv