# Scatter Plot - Data Analysis Notebook

In [1]:
import pandas as pd
import json
import matplotlib.pyplot as plt

In [2]:
# Read json files from ../src/json/fips.json
# FIPS 10-4 to Country Name mapping
with open('../src/json/fips.json', 'r') as f:
    fips = json.load(f)

In [3]:
# Function to convert 2-letter FIPS 10-4 country codes to country names
def code_to_country(code):
    try:
        country = fips[code]
        return country
    except:
        raise ValueError(f"Invalid country code: {code}")

In [4]:
# Load the mentions dataset from data/GDELT/weekly_media_attention_query_class34_better_disambiguation.csv
# The old dataset
# path_mentions = "../data/GDELT/weekly_media_attention_query_class34_better_disambiguation.csv"

# The new one
# path_mentions = "../data/GDELT/2026_weekly_media_attention_query_class34_better_disambiguation.csv"
# df_mentions = pd.read_csv(path_mentions)
# df_mentions.head()

gdelt_path = "../data/GDELT/"
df_keys = pd.read_parquet(gdelt_path + "gdelt_keys.parquet")
df_keys.head()

,conflict_id,mention_week,conflict_country,actor1_country,actor2_country,media_country
0,0,2026-01-12,UK,UNK,GBR,UP
1,1,2026-01-12,FR,FRA,USA,US
2,2,2026-01-12,IS,GBR,UNK,UK
3,3,2026-01-12,UP,EUR,RUS,UK
4,4,2026-01-12,EZ,SVK,UNK,EZ

In [5]:
df_volume = pd.read_parquet(gdelt_path + "gdelt_volume_metrics.parquet")
df_volume.head()

   conflict_id  mentions_count  distinct_events  distinct_media_sources
0            0              16               13                      11
1            1             101               28                      71
2            2               8                8                       5
3            3             208                5                     105
4            4               6                5                       4

In [6]:
df_mention_types = pd.read_parquet(gdelt_path + "gdelt_conflict_types.parquet")
df_mention_types.head()

,conflict_id,verbal_conflict_mentions,material_conflict_mentions,verbal_conflict_unique_events,material_conflict_unique_events
0,0,3,13,3,10
1,1,41,60,11,17
2,2,6,2,6,2
3,3,207,1,4,1
4,4,5,1,4,1

In [7]:
# join just df_keys and df_mention_types on conflict_id
df_mentions = pd.merge(df_keys, df_mention_types, on='conflict_id')
df_mentions.head()

,conflict_id,mention_week,conflict_country,actor1_country,actor2_country,media_country,verbal_conflict_mentions,material_conflict_mentions,verbal_conflict_unique_events,material_conflict_unique_events
0,0,2026-01-12,UK,UNK,GBR,UP,3,13,3,10
1,1,2026-01-12,FR,FRA,USA,US,41,60,11,17
2,2,2026-01-12,IS,GBR,UNK,UK,6,2,6,2
3,3,2026-01-12,UP,EUR,RUS,UK,207,1,4,1
4,4,2026-01-12,EZ,SVK,UNK,EZ,5,1,4,1

In [8]:
df_mentions = pd.merge(df_mentions, df_volume, on='conflict_id')
df_mentions.head()

,conflict_id,mention_week,conflict_country,actor1_country,actor2_country,media_country,verbal_conflict_mentions,material_conflict_mentions,verbal_conflict_unique_events,material_conflict_unique_events,mentions_count,distinct_events,distinct_media_sources
0,0,2026-01-12,UK,UNK,GBR,UP,3,13,3,10,16,13,11
1,1,2026-01-12,FR,FRA,USA,US,41,60,11,17,101,28,71
2,2,2026-01-12,IS,GBR,UNK,UK,6,2,6,2,8,8,5
3,3,2026-01-12,UP,EUR,RUS,UK,207,1,4,1,208,5,105
4,4,2026-01-12,EZ,SVK,UNK,EZ,5,1,4,1,6,5,4

In [9]:
# Print unique values in the 'mention_week' column sorted by most recent date
print(sorted(df_mentions['mention_week'].unique(), reverse=True))

['2026-01-12', '2026-01-05', '2025-12-29', '2025-12-22', '2025-12-15', '2025-12-08', '2025-12-01', '2025-11-24', '2025-11-17', '2025-11-10', '2025-11-03', '2025-10-27', '2025-10-20', '2025-10-13', '2025-10-06', '2025-09-29', '2025-09-22', '2025-09-15', '2025-09-08', '2025-09-01', '2025-08-25', '2025-08-18', '2025-08-11', '2025-08-04', '2025-07-28', '2025-07-21', '2025-07-14', '2025-07-07', '2025-06-30', '2025-06-09', '2025-06-02', '2025-05-26', '2025-05-19', '2025-05-12', '2025-05-05', '2025-04-28', '2025-04-21', '2025-04-14', '2025-04-07', '2025-03-31', '2025-03-24', '2025-03-17', '2025-03-10', '2025-03-03', '2025-02-24', '2025-02-17', '2025-02-10', '2025-02-03', '2025-01-27', '2025-01-20', '2025-01-13', '2025-01-06', '2024-12-30', '2024-12-23', '2024-12-16', '2024-12-09', '2024-12-02', '2024-11-25', '2024-11-18', '2024-11-11', '2024-11-04', '2024-10-28', '2024-10-21', '2024-10-14', '2024-10-07', '2024-09-30', '2024-09-23', '2024-09-16', '2024-09-09', '2024-09-02', '2024-08-26', '2024-08-19', '2024-08-12', '2024-08-05', '2024-07-29', '2024-07-22', '2024-07-15', '2024-07-08', '2024-07-01', '2024-06-24', '2024-06-17', '2024-06-10', '2024-06-03', '2024-05-27', '2024-05-20', '2024-05-13', '2024-05-06', '2024-04-29', '2024-04-22', '2024-04-15', '2024-04-08', '2024-04-01', '2024-03-25', '2024-03-18', '2024-03-11', '2024-03-04', '2024-02-26', '2024-02-19', '2024-02-12', '2024-02-05', '2024-01-29', '2024-01-22', '2024-01-15', '2024-01-08', '2024-01-01', '2023-12-25', '2023-12-18', '2023-12-11', '2023-12-04', '2023-11-27', '2023-11-20', '2023-11-13', '2023-11-06', '2023-10-30', '2023-10-23', '2023-10-16', '2023-10-09', '2023-10-02', '2023-09-25', '2023-09-18', '2023-09-11', '2023-09-04', '2023-08-28', '2023-08-21', '2023-08-14', '2023-08-07', '2023-07-31', '2023-07-24', '2023-07-17', '2023-07-10', '2023-07-03', '2023-06-26', '2023-06-19', '2023-06-12', '2023-06-05', '2023-05-29', '2023-05-22', '2023-05-15', '2023-05-08', '2023-05-01', '2023-04-24', '2023-04-17', '2023-04-10', '2023-04-03', '2023-03-27', '2023-03-20', '2023-03-13', '2023-03-06', '2023-02-27', '2023-02-20', '2023-02-13', '2023-02-06', '2023-01-30', '2023-01-23', '2023-01-16', '2023-01-09', '2023-01-02', '2022-12-26', '2022-12-19', '2022-12-12', '2022-12-05', '2022-11-28', '2022-11-21', '2022-11-14', '2022-11-07', '2022-10-31', '2022-10-24', '2022-10-17', '2022-10-10', '2022-10-03', '2022-09-26', '2022-09-19', '2022-09-12', '2022-09-05', '2022-08-29', '2022-08-22', '2022-08-15', '2022-08-08', '2022-08-01', '2022-07-25', '2022-07-18', '2022-07-11', '2022-07-04', '2022-06-27', '2022-06-20', '2022-06-13', '2022-06-06', '2022-05-30', '2022-05-23', '2022-05-16', '2022-05-09', '2022-05-02', '2022-04-25', '2022-04-18', '2022-04-11', '2022-04-04', '2022-03-28', '2022-03-21', '2022-03-14', '2022-03-07', '2022-02-28', '2022-02-21', '2022-02-14', '2022-02-07', '2022-01-31', '2022-01-24', '2022-01-17', '2022-01-10', '2022-01-03', '2021-12-27', '2021-12-20', '2021-12-13', '2021-12-06', '2021-11-29', '2021-11-22', '2021-11-15', '2021-11-08', '2021-11-01', '2021-10-25', '2021-10-18', '2021-10-11', '2021-10-04', '2021-09-27', '2021-09-20', '2021-09-13', '2021-09-06', '2021-08-30', '2021-08-23', '2021-08-16', '2021-08-09', '2021-08-02', '2021-07-26', '2021-07-19', '2021-07-12', '2021-07-05', '2021-06-28', '2021-06-21', '2021-06-14', '2021-06-07', '2021-05-31', '2021-05-24', '2021-05-17', '2021-05-10', '2021-05-03', '2021-04-26', '2021-04-19', '2021-04-12', '2021-04-05', '2021-03-29', '2021-03-22', '2021-03-15', '2021-03-08', '2021-03-01', '2021-02-22', '2021-02-15', '2021-02-08', '2021-02-01', '2021-01-25', '2021-01-18', '2021-01-11', '2021-01-04', '2020-12-28', '2020-12-21', '2020-12-14', '2020-12-07', '2020-11-30', '2020-11-23', '2020-11-16', '2020-11-09', '2020-11-02', '2020-10-26', '2020-10-19', '2020-10-12', '2020-10-05', '2020-09-28', '2020-09-21', '2020-09-14', '2020-09-07', '2020-08-31', '2020-08-24', '2020-08-17', '2020-08-10', '2020-08-03', '2020-07-27', '2020-07-20', '2020-07-13', '2020-07-06', '2020-06-29', '2020-06-22', '2020-06-15', '2020-06-08', '2020-06-01', '2020-05-25', '2020-05-18', '2020-05-11', '2020-05-04', '2020-04-27', '2020-04-20', '2020-04-13', '2020-04-06', '2020-03-30', '2020-03-23', '2020-03-16', '2020-03-09', '2020-03-02', '2020-02-24', '2020-02-17', '2020-02-10', '2020-02-03', '2020-01-27', '2020-01-20', '2020-01-13', '2020-01-06', '2019-12-30', '2019-12-23', '2019-12-16', '2019-12-09', '2019-12-02', '2019-11-25', '2019-11-18', '2019-11-11', '2019-11-04', '2019-10-28', '2019-10-21', '2019-10-14', '2019-10-07', '2019-09-30', '2019-09-23', '2019-09-16', '2019-09-09', '2019-09-02', '2019-08-26', '2019-08-19', '2019-08-12', '2019-08-05', '2019-07-29', '2019-07-22', '2019-07-15', '2019-07-08', '2019-07-01', '2019-06-24', '2019-06-17', '2019-06-10', '2019-06-03', '2019-05-27', '2019-05-20', '2019-05-13', '2019-05-06', '2019-04-29', '2019-04-22', '2019-04-15', '2019-04-08', '2019-04-01', '2019-03-25', '2019-03-18', '2019-03-11', '2019-03-04', '2019-02-25', '2019-02-18', '2019-02-11', '2019-02-04', '2019-01-28', '2019-01-21', '2019-01-14', '2019-01-07', '2018-12-31', '2018-12-24', '2018-12-17', '2018-12-10', '2018-12-03', '2018-11-26', '2018-11-19', '2018-11-12', '2018-11-05', '2018-10-29', '2018-10-22', '2018-10-15', '2018-10-08', '2018-10-01', '2018-09-24', '2018-09-17', '2018-09-10', '2018-09-03', '2018-08-27', '2018-08-20', '2018-08-13', '2018-08-06', '2018-07-30', '2018-07-23', '2018-07-16', '2018-07-09', '2018-07-02', '2018-06-25', '2018-06-18', '2018-06-11', '2018-06-04', '2018-05-28', '2018-05-21', '2018-05-14', '2018-05-07', '2018-04-30', '2018-04-23', '2018-04-16', '2018-04-09', '2018-04-02', '2018-03-26', '2018-03-19', '2018-03-12', '2018-03-05', '2018-02-26', '2018-02-19', '2018-02-12', '2018-02-05', '2018-01-29', '2018-01-22', '2018-01-15', '2018-01-08', '2018-01-01', '2017-12-25', '2017-12-18', '2017-12-11', '2017-12-04', '2017-11-27', '2017-11-20', '2017-11-13', '2017-11-06', '2017-10-30', '2017-10-23', '2017-10-16', '2017-10-09', '2017-10-02', '2017-09-25', '2017-09-18', '2017-09-11', '2017-09-04', '2017-08-28', '2017-08-21', '2017-08-14', '2017-08-07', '2017-07-31', '2017-07-24', '2017-07-17', '2017-07-10', '2017-07-03', '2017-06-26', '2017-06-19', '2017-06-12', '2017-06-05', '2017-05-29', '2017-05-22', '2017-05-15', '2017-05-08', '2017-05-01', '2017-04-24', '2017-04-17', '2017-04-10', '2017-04-03', '2017-03-27', '2017-03-20', '2017-03-13', '2017-03-06', '2017-02-27', '2017-02-20', '2017-02-13', '2017-02-06', '2017-01-30', '2017-01-23', '2017-01-16', '2017-01-09', '2017-01-02', '2016-12-26', '2016-12-19', '2016-12-12', '2016-12-05', '2016-11-28', '2016-11-21', '2016-11-14', '2016-11-07', '2016-10-31', '2016-10-24', '2016-10-17', '2016-10-10', '2016-10-03', '2016-09-26', '2016-09-19', '2016-09-12', '2016-09-05', '2016-08-29', '2016-08-22', '2016-08-15', '2016-08-08', '2016-08-01', '2016-07-25', '2016-07-18', '2016-07-11', '2016-07-04', '2016-06-27', '2016-06-20', '2016-06-13', '2016-06-06', '2016-05-30', '2016-05-23', '2016-05-16', '2016-05-09', '2016-05-02', '2016-04-25', '2016-04-18', '2016-04-11', '2016-04-04', '2016-03-28', '2016-03-21', '2016-03-14', '2016-03-07', '2016-02-29', '2016-02-22', '2016-02-15', '2016-02-08', '2016-02-01', '2016-01-25', '2016-01-18', '2016-01-11', '2016-01-04', '2015-12-28', '2015-12-21', '2015-12-14', '2015-12-07', '2015-11-30', '2015-11-23', '2015-11-16', '2015-11-09', '2015-11-02', '2015-10-26', '2015-10-19', '2015-10-12', '2015-10-05', '2015-09-28', '2015-09-21', '2015-09-14', '2015-09-07', '2015-08-31', '2015-08-24', '2015-08-17', '2015-08-10', '2015-08-03', '2015-07-27', '2015-07-20', '2015-07-13', '2015-07-06', '2015-06-29', '2015-06-22', '2015-06-15', '2015-06-08', '2015-06-01', '2015-05-25', '2015-05-18', '2015-05-11', '2015-05-04', '2015-04-27', '2015-04-20', '2015-04-13', '2015-04-06', '2015-03-30', '2015-03-23', '2015-03-16', '2015-03-09', '2015-03-02', '2015-02-23', '2015-02-16']

In [10]:
# Since we are in 2026 now and we want to analyze 2025 data,
# we only keep GDELT data up to the 2025-12-31 week
df_mentions = df_mentions[df_mentions['mention_week'] <= '2025-12-31']

In [11]:
# Load the fatalities dataset from data/ACLED/number_of_reported_fatalities_by_country-year_as-of-09Jan2026.CSV
path_fatalities = "../data/ACLED/number_of_reported_fatalities_by_country-year_as-of-09Jan2026.CSV"
df_fatalities = pd.read_csv(path_fatalities, encoding='utf-8', sep=';')

# Display the first few rows of the dataframe
df_fatalities.head()

       COUNTRY  YEAR  FATALITIES
0  Afghanistan  2017       36360
1  Afghanistan  2018       42991
2  Afghanistan  2019       41419
3  Afghanistan  2020       30977
4  Afghanistan  2021       42425

In [12]:
# Removing the rows with YEAR == 2026
df_fatalities = df_fatalities[df_fatalities['YEAR'] != 2026]
df_fatalities.head(10)

                  COUNTRY  YEAR  FATALITIES
0             Afghanistan  2017       36360
1             Afghanistan  2018       42991
2             Afghanistan  2019       41419
3             Afghanistan  2020       30977
4             Afghanistan  2021       42425
5             Afghanistan  2022        4152
6             Afghanistan  2023        1152
7             Afghanistan  2024        1362
8             Afghanistan  2025         915
10  Akrotiri and Dhekelia  2018           0

Create a new dataset with country name, number of mentions, and number of fatalities for the scatter plot visualization.

The year will be also kept to allow visualizing the evolution over time.

Pay attention: here **we are considering all the conflict mentions**, not only material conflict ones.

In [13]:
# First, add column YEAR (column 'mention_week' contains the year at the start)
df_mentions_year = df_mentions.copy()
df_mentions_year['year'] = df_mentions_year['mention_week'].str[:4].astype(int)
# Remove entries with country codes not in fips keys
df_mentions_year = df_mentions_year[df_mentions_year['conflict_country'].isin(set(fips.keys()))]
# Aggregate the number of mentions by country and year
mentions_agg = df_mentions_year.groupby(['conflict_country', 'year'])['mentions_count'].sum().reset_index()
# Rename columns for clarity
mentions_agg.columns = ['COUNTRY', 'YEAR', 'MENTIONS']
# Map country codes to country names
mentions_agg['COUNTRY'] = mentions_agg['COUNTRY'].apply(code_to_country)
# If a country appears multiple times, sum the mentions
mentions_agg = mentions_agg.groupby(['COUNTRY', 'YEAR'])['MENTIONS'].sum().reset_index()

# Select relevant columns
fatalities_agg = df_fatalities[['COUNTRY', 'YEAR', 'FATALITIES']]
# Merge the two datasets on country name
merged_df = pd.merge(mentions_agg, fatalities_agg, on=['COUNTRY', 'YEAR'], how='inner')
# Display the merged dataframe
merged_df.head()

       COUNTRY  YEAR  MENTIONS  FATALITIES
0  Afghanistan  2017    989643       36360
1  Afghanistan  2018    902235       42991
2  Afghanistan  2019    553219       41419
3  Afghanistan  2020    368395       30977
4  Afghanistan  2021    914148       42425

In [14]:
# Show highest values of mentions and fatalities
print("Top 10 countries by mentions in 2025:")
print(merged_df.sort_values(by='MENTIONS', ascending=False).head(10))
print()

print("Top 10 countries by fatalities in 2025:")
print(merged_df.sort_values(by='FATALITIES', ascending=False).head(10))
print()

print("Bottom 10 countries by mentions in 2025:")
print(merged_df.sort_values(by='MENTIONS', ascending=True).head(10))
print()

print("Bottom 10 countries by fatalities in 2025:")
print(merged_df.sort_values(by='FATALITIES', ascending=True).head(10))

Top 10 countries by mentions in 2025:
            COUNTRY  YEAR  MENTIONS  FATALITIES
1684  United States  2020  16123908          74
1685  United States  2021  13000763          87
1687  United States  2023  12237312          66
1688  United States  2024  11765870          33
1689  United States  2025  10965487          54
1686  United States  2022   9646538          98
778          Israel  2024   6790269          99
777          Israel  2023   5567365        1772
1331         Russia  2022   5016223          97
772          Israel  2018   4263326           7

Top 10 countries by fatalities in 2025:
          COUNTRY  YEAR  MENTIONS  FATALITIES
1668      Ukraine  2025   1792913       78347
1667      Ukraine  2024   2030567       73570
750          Iraq  2016   1890947       56032
1549        Syria  2017   2713455       54122
1     Afghanistan  2018    902235       42991
4     Afghanistan  2021    914148       42425
2     Afghanistan  2019    553219       41419
1665      Ukraine  2022   3944455       40530
1666      Ukraine  2023   2678425       39762
0     Afghanistan  2017    989643       36360

Bottom 10 countries by mentions in 2025:
                                           COUNTRY  YEAR  MENTIONS  FATALITIES
529                               Falkland Islands  2019         6           0
1362                     Saint Pierre and Miquelon  2024         8           0
53                                        Anguilla  2023         8           0
1361                     Saint Pierre and Miquelon  2021        10           0
528                               Falkland Islands  2018        11           0
1352                         Saint Kitts and Nevis  2025        12           0
1177                                Norfolk Island  2021        13           0
1195                      Northern Mariana Islands  2025        14           0
556                                  French Guiana  2019        21           0
1347  Saint Helena, Ascension and Tristan da Cunha  2021        22           0

Bottom 10 countries by fatalities in 2025:
           COUNTRY  YEAR  MENTIONS  FATALITIES
853         Kuwait  2018     39140           0
1729       Vietnam  2021     50269           0
58      Antarctica  2024      1526           0
1706       Vanuatu  2021       335           0
1708       Vanuatu  2023       597           0
1709       Vanuatu  2024       669           0
1710  Vatican City  2020      3040           0
1711  Vatican City  2021      5513           0
57      Antarctica  2023      3381           0
1774      eSwatini  2018      2551           0

In [15]:
# Save the merged dataset to a new CSV file
output_path = "../data/processed/scatter_plot.csv"
merged_df.to_csv(output_path, index=False)
print(f"Merged dataset saved to {output_path}")

Merged dataset saved to ../data/processed/scatter_plot.csv

### Taking only the material conflict mentions and not the verbal conflict ones

In [16]:
# Create a new dataset with country name, number of mentions in 2025, and number of fatalities in 2025

df_mentions_year = df_mentions.copy()
df_mentions_year['year'] = df_mentions_year['mention_week'].str[:4].astype(int)
df_mentions_year = df_mentions_year[df_mentions_year['conflict_country'].isin(set(fips.keys()))]
mentions_agg = df_mentions_year.groupby(['conflict_country', 'year'])['material_conflict_mentions'].sum().reset_index()
mentions_agg.columns = ['COUNTRY', 'YEAR', 'MENTIONS']
mentions_agg['COUNTRY'] = mentions_agg['COUNTRY'].apply(code_to_country)
mentions_agg = mentions_agg.groupby(['COUNTRY', 'YEAR'])['MENTIONS'].sum().reset_index()

# Select relevant columns
fatalities_agg = df_fatalities[['COUNTRY', 'YEAR', 'FATALITIES']]
# Merge the two datasets on country name
merged_df = pd.merge(mentions_agg, fatalities_agg, on=['COUNTRY', 'YEAR'], how='inner')
# Display the merged dataframe
merged_df.head()

       COUNTRY  YEAR  MENTIONS  FATALITIES
0  Afghanistan  2017    713597       36360
1  Afghanistan  2018    680361       42991
2  Afghanistan  2019    376789       41419
3  Afghanistan  2020    246811       30977
4  Afghanistan  2021    563730       42425

In [17]:
# Save the merged dataset to a new CSV file
output_path = "../data/processed/scatter_plot_material_conflict.csv"
merged_df.to_csv(output_path, index=False)
print(f"Merged dataset saved to {output_path}")

Merged dataset saved to ../data/processed/scatter_plot_material_conflict.csv