In [55]:
import pandas as pd

In [ ]:
# FIPS 10-4 to Country Name mapping
fips_to_country = {
    'AA': 'Aruba',
    'AC': 'Antigua and Barbuda',
    'AD': 'Akrotiri',
    'AE': 'United Arab Emirates',
    'AF': 'Afghanistan',
    'AG': 'Algeria',
    'AJ': 'Azerbaijan',
    'AL': 'Albania',
    'AM': 'Armenia',
    'AN': 'Andorra',
    'AO': 'Angola',
    'AQ': 'American Samoa',
    'AR': 'Argentina',
    'AS': 'Australia',
    'AT': 'Ashmore and Cartier Islands',
    'AU': 'Austria',
    'AV': 'Anguilla',
    'AY': 'Antarctica',
    'BA': 'Bahrain',
    'BB': 'Barbados',
    'BC': 'Botswana',
    'BD': 'Bermuda',
    'BE': 'Belgium',
    'BF': 'Bahamas',
    'BG': 'Bangladesh',
    'BH': 'Belize',
    'BK': 'Bosnia and Herzegovina',
    'BL': 'Bolivia',
    'BM': 'Burma',
    'BN': 'Benin',
    'BO': 'Belarus',
    'BP': 'Solomon Islands',
    'BQ': 'Navassa Island',
    'BR': 'Brazil',
    'BT': 'Bhutan',
    'BU': 'Bulgaria',
    'BV': 'Bouvet Island',
    'BX': 'Brunei',
    'BY': 'Burundi',
    'CA': 'Canada',
    'CB': 'Cambodia',
    'CD': 'Chad',
    'CE': 'Sri Lanka',
    'CF': 'Republic of the Congo',
    'CG': 'Democratic Republic of the Congo',
    'CH': 'China',
    'CI': 'Cile',
    'CJ': 'Cayman Islands',
    'CK': 'Cocos (Keeling) Islands',
    'CM': 'Cameroon',
    'CN': 'Comoros',
    'CO': 'Colombia',
    'CQ': 'Northern Mariana Islands',
    'CR': 'Coral Sea Islands',
    'CS': 'Costa Rica',
    'CT': 'Central African Republic',
    'CU': 'Cuba',
    'CV': 'Cape Verde',
    'CW': 'Cook Islands',
    'CY': 'Cyprus',
    'DA': 'Denmark',
    'DJ': 'Djibouti',
    'DO': 'Dominica',
    'DR': 'Dominican Republic',
    'EC': 'Ecuador',
    'EE': 'European Union',
    'EG': 'Egypt',
    'EI': 'Ireland',
    'EK': 'Equatorial Guinea',
    'EN': 'Estonia',
    'ER': 'Eritrea',
    'ES': 'El Salvador',
    'ET': 'Ethiopia',
    'EU': 'Europa Island',
    'EZ': 'Czechia',
    'FG': 'French Guiana',
    'FI': 'Finland',
    'FJ': 'Fiji',
    'FK': 'Falkland Islands',
    'FM': 'Micronesia',
    'FO': 'Faroe Islands',
    'FP': 'French Polynesia',
    'FR': 'France',
    'FS': 'French Southern and Antarctic Lands',
    'GA': 'Gambia',
    'GB': 'Gabon',
    'GG': 'Georgia',
    'GH': 'Ghana',
    'GI': 'Gibraltar',
    'GJ': 'Grenada',
    'GK': 'Guernsey',
    'GL': 'Greenland',
    'GM': 'Germany',
    'GO': 'Glorioso Islands',
    'GP': 'Guadeloupe',
    'GQ': 'Guam',
    'GR': 'Greece',
    'GT': 'Guatemala',
    'GV': 'Guinea',
    'GY': 'Guyana',
    'GZ': 'Palestine',
    'HA': 'Haiti',
    'HK': 'Hong Kong',
    'HM': 'Heard Island and McDonald Islands',
    'HO': 'Honduras',
    'HR': 'Croatia',
    'HU': 'Hungary',
    'IC': 'Iceland',
    'ID': 'Indonesia',
    'IM': 'Isle of Man',
    'IN': 'India',
    'IO': 'British Indian Ocean Territory',
    'IP': 'Clipperton Island',
    'IR': 'Iran',
    'IS': 'Israel',
    'IT': 'Italy',
    'IV': 'Côte d’Ivoire',
    'IZ': 'Iraq',
    'JA': 'Japan',
    'JE': 'Jersey',
    'JM': 'Jamaica',
    'JN': 'Jan Mayen',
    'JO': 'Jordan',
    'JU': 'Juan de Nova Island',
    'KE': 'Kenya',
    'KG': 'Kyrgyzstan',
    'KN': 'North Korea',
    'KR': 'Kiribati',
    'KS': 'South Korea',
    'KT': 'Christmas Island',
    'KU': 'Kuwait',
    'KV': 'Kosovo',
    'KZ': 'Kazakhstan',
    'LA': 'Laos',
    'LE': 'Lebanon',
    'LG': 'Latvia',
    'LH': 'Lithuania',
    'LI': 'Liberia',
    'LO': 'Slovakia',
    'LS': 'Lichtenstein',
    'LT': 'Lesotho',
    'LU': 'Luxembourg',
    'LY': 'Libya',
    'MA': 'Madagascar',
    'MB': 'Martinique',
    'MC': 'Macau',
    'MD': 'Moldova',
    'MF': 'Mayotte',
    'MG': 'Mongolia',
    'MH': 'Montserrat',
    'MI': 'Malawi',
    'MJ': 'Montenegro',
    'MK': 'North Macedonia',
    'ML': 'Mali',
    'MN': 'Monaco',
    'MO': 'Morocco',
    'MP': 'Mauritius',
    'MR': 'Mauritania',
    'MT': 'Malta',
    'MU': 'Oman',
    'MV': 'Maldives',
    'MX': 'Mexico',
    'MY': 'Malaysia',
    'MW': 'Montenegro',
    'MZ': 'Mozambique',
    'NC': 'New Caledonia',
    'NE': 'Niue',
    'NF': 'Norfolk Island',
    'NG': 'Niger',
    'NH': 'Vanuatu',
    'NI': 'Nigeria',
    'NL': 'Netherlands',
    'NN': 'Sint Maarten',
    'NO': 'Norway',
    'NP': 'Nepal',
    'NR': 'Nauru',
    'NS': 'Suriname',
    'NT': 'Netherlands Antilles',
    'NU': 'Nicaragua',
    'NZ': 'New Zealand',
    'OD': 'South Sudan',
    'PA': 'Paraguay',
    'PC': 'Pitcairn Islands',
    'PE': 'Peru',
    'PF': 'Paracel Islands',
    'PG': 'Spratly Islands',
    'PJ': 'Etorofu, Habomai, Shikotan, Kunashiri Islands',
    'PK': 'Pakistan',
    'PL': 'Poland',
    'PM': 'Panama',
    'PO': 'Portugal',
    'PP': 'Papua New Guinea',
    'PS': 'Palau',
    'PU': 'Guinnea-Bissau',
    'QA': 'Qatar',
    'RE': 'Réunion',
    'RI': 'Serbia',
    'RM': 'Marshall Islands',
    'RN': 'Saint Martin',
    'RO': 'Romania',
    'RP': 'Philippines',
    'RQ': 'Puerto Rico',
    'RS': 'Russia',
    'RW': 'Rwanda',
    'SA': 'Saudi Arabia',
    'SB': 'Saint Pierre and Miquelon',
    'SC': 'Saint Kitts and Nevis',
    'SE': 'Seychelles',
    'SF': 'South Africa',
    'SG': 'Singapore',
    'SH': 'Saint Helena, Ascension, and Tristan da Cunha',
    'SI': 'Slovenia',
    'SL': 'Sierra Leone',
    'SM': 'San Marino',
    'SN': 'Singapore',
    'SO': 'Somalia',
    'SP': 'Spain',
    'SR': 'Suriname',
    'ST': 'Saint Lucia',
    'SU': 'Sudan',
    'SV': 'Svalbard',
    'SW': 'Sweden',
    'SX': 'South Georgia and the South Sandwich Islands',
    'SY': 'Syria',
    'SZ': 'Switzerland',
    'TB': 'Saint Barthelemy',
    'TD': 'Trinidad and Tobago',
    'TE': 'Tromelin Island',
    'TH': 'Thailand',
    'TI': 'Tajikistan',
    'TK': 'Turks and Caicos Islands',
    'TL': 'Tokelau',
    'TN': 'Tonga',
    'TO': 'Togo',
    'TP': 'Sao Tome and Principe',
    'TS': 'Tunisia',
    'TT': 'Timor-Leste',
    'TU': 'Turkey',
    'TV': 'Tuvalu',
    'TW': 'Taiwan',
    'TX': 'Turkmenistan',
    'TZ': 'Tanzania',
    'UC': 'Curacao',
    'UG': 'Uganda',
    'UK': 'United Kingdom',
    'UM': 'U.S. Minor Outlying Islands',
    'UP': 'Ukraine',
    'US': 'United States',
    'UV': 'Burkina Faso',
    'UY': 'Uruguay',
    'UZ': 'Uzbekistan',
    'VC': 'Saint Vincent and the Grenadines',
    'VE': 'Venezuela',
    'VI': 'British Virgin Islands',
    'VM': 'Vietnam',
    'VQ': 'U.S. Virgin Islands',
    'VT': 'Vatican City',
    'WA': 'Namibia',
    'WE': 'Palestine',
    'WF': 'Wallis and Futuna',
    'WI': 'Western Sahara',
    'WQ': 'Wake Island',
    'WS': 'Samoa',
    'WZ': 'Eswatini',
    'YM': 'Yemen',
    'ZA': 'Zambia',
    'ZI': 'Zimbabwe',
}

In [57]:
# Function to convert 2-letter country codes to country names
def code_to_country(code):
    try:
        country = fips_to_country[code]
        return country
    except:
        raise ValueError(f"Invalid country code: {code}")

In [58]:
# print alpha_2 codes and country names for verification
alpha2 = set([country.alpha_2 for country in pc.countries])
print(sorted(list(alpha2)))

['AD', 'AE', 'AF', 'AG', 'AI', 'AL', 'AM', 'AO', 'AQ', 'AR', 'AS', 'AT', 'AU', 'AW', 'AX', 'AZ', 'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BL', 'BM', 'BN', 'BO', 'BQ', 'BR', 'BS', 'BT', 'BV', 'BW', 'BY', 'BZ', 'CA', 'CC', 'CD', 'CF', 'CG', 'CH', 'CI', 'CK', 'CL', 'CM', 'CN', 'CO', 'CR', 'CU', 'CV', 'CW', 'CX', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'EH', 'ER', 'ES', 'ET', 'FI', 'FJ', 'FK', 'FM', 'FO', 'FR', 'GA', 'GB', 'GD', 'GE', 'GF', 'GG', 'GH', 'GI', 'GL', 'GM', 'GN', 'GP', 'GQ', 'GR', 'GS', 'GT', 'GU', 'GW', 'GY', 'HK', 'HM', 'HN', 'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IM', 'IN', 'IO', 'IQ', 'IR', 'IS', 'IT', 'JE', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KP', 'KR', 'KW', 'KY', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'LY', 'MA', 'MC', 'MD', 'ME', 'MF', 'MG', 'MH', 'MK', 'ML', 'MM', 'MN', 'MO', 'MP', 'MQ', 'MR', 'MS', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NC', 'NE', 'NF', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 'NU', 'NZ', 'OM', 'PA', 'PE', 'PF', 'PG', 'PH', 'PK', 'PL', 'PM', 'PN', 'PR', 'PS', 'PT', 'PW', 'PY', 'QA', 'RE', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SD', 'SE', 'SG', 'SH', 'SI', 'SJ', 'SK', 'SL', 'SM', 'SN', 'SO', 'SR', 'SS', 'ST', 'SV', 'SX', 'SY', 'SZ', 'TC', 'TD', 'TF', 'TG', 'TH', 'TJ', 'TK', 'TL', 'TM', 'TN', 'TO', 'TR', 'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'UM', 'US', 'UY', 'UZ', 'VA', 'VC', 'VE', 'VG', 'VI', 'VN', 'VU', 'WF', 'WS', 'YE', 'YT', 'ZA', 'ZM', 'ZW']

In [59]:
# Load the mentions dataset from data/GDELT/conflict_data.csv
path_mentions = "../data/GDELT/conflict_data.csv"
df_mentions = pd.read_csv(path_mentions)

# Display the first few rows of the dataframe
df_mentions.head()

,week,conflict_country,media_country,mentions_count,avg_tone,avg_event_impact
0,2025-12-22,LU,USA / International,3,-2.746214,-10.000000
1,2025-12-22,IN,UK,26,-5.256288,-9.192308
2,2025-12-22,AJ,USA / International,107,-5.563384,-9.677570
3,2025-12-22,SL,USA / International,4,-6.421062,-10.000000
4,2025-12-22,HK,France,2,-4.116866,-10.000000

In [60]:
# Load the fatalities dataset from data/ACLED/number_of_reported_fatalities_by_country-year_as-of-12Dec2025.csv
path_fatalities = "../data/ACLED/number_of_reported_fatalities_by_country-year_as-of-12Dec2025.csv"
df_fatalities = pd.read_csv(path_fatalities, encoding='utf-8', sep=';')

# Display the first few rows of the dataframe
df_fatalities.head()

       COUNTRY  YEAR  FATALITIES
0  Afghanistan  2017       36360
1  Afghanistan  2018       42991
2  Afghanistan  2019       41419
3  Afghanistan  2020       30977
4  Afghanistan  2021       42425

In [61]:
# Create a new dataset with country name, number of mentions in 2025, and number of fatalities in 2025

# First, filter the mentions dataset for the year 2025 (column 'week' starts with 2025)
df_mentions_2025 = df_mentions[df_mentions['week'].str.startswith('2025')]
# Remove lines with country codes not in pcountries
df_mentions_2025 = df_mentions_2025[df_mentions_2025['conflict_country'].isin(set(fips_to_country.keys()))]
# Aggregate the number of mentions by country
mentions_agg = df_mentions_2025.groupby('conflict_country')['mentions_count'].sum().reset_index()
# Rename columns for clarity
mentions_agg.columns = ['COUNTRY', 'MENTIONS']
# Map country codes to country names
mentions_agg['COUNTRY'] = mentions_agg['COUNTRY'].apply(code_to_country)
# If a country appears multiple times, sum the mentions
mentions_agg = mentions_agg.groupby('COUNTRY')['MENTIONS'].sum().reset_index()

# Filter the fatalities dataset for the year 2025
df_fatalities_2025 = df_fatalities[df_fatalities['YEAR'] == 2025]
# Select relevant columns
fatalities_agg = df_fatalities_2025[['COUNTRY', 'FATALITIES']]
# Merge the two datasets on country name
merged_df = pd.merge(mentions_agg, fatalities_agg, on='COUNTRY', how='inner')
# Display the merged dataframe
merged_df.head()

          COUNTRY  MENTIONS  FATALITIES
0     Afghanistan     59012         886
1         Albania     11062           0
2         Algeria      6080          32
3  American Samoa        91           0
4         Andorra       331           0

In [62]:
# Show highest values of mentions and fatalities
print("Top 10 countries by mentions in 2025:")
print(merged_df.sort_values(by='MENTIONS', ascending=False).head(10))
print()

print("Top 10 countries by fatalities in 2025:")
print(merged_df.sort_values(by='FATALITIES', ascending=False).head(10))
print()

print("Bottom 10 countries by mentions in 2025:")
print(merged_df.sort_values(by='MENTIONS', ascending=True).head(10))
print()

print("Bottom 10 countries by fatalities in 2025:")
print(merged_df.sort_values(by='FATALITIES', ascending=True).head(10))

Top 10 countries by mentions in 2025:
            COUNTRY  MENTIONS  FATALITIES
178   United States   2785606          50
83           Israel   1533653          47
142          Russia    745245        1797
175         Ukraine    700425       73018
177  United Kingdom    385296           3
77            India    298701        1115
10        Australia    287236           0
129        Pakistan    206976        5025
164           Syria    153377        7779
31           Canada    146316           0

Top 10 countries by fatalities in 2025:
       COUNTRY  MENTIONS  FATALITIES
175    Ukraine    700425       73018
160      Sudan     66483       17510
131  Palestine    111810       16833
124    Nigeria    104995       11512
154    Somalia     14316        9366
110     Mexico    134232        7857
164      Syria    153377        7779
24      Brazil     64340        7367
51    Ethiopia      7552        5940
129   Pakistan    206976        5025

Bottom 10 countries by mentions in 2025:
                      COUNTRY  MENTIONS  FATALITIES
127  Northern Mariana Islands        22           0
57              French Guiana        30           0
53              Faroe Islands        32           0
52           Falkland Islands        37           0
25     British Virgin Islands        48           0
58           French Polynesia        52           0
144     Saint Kitts and Nevis        52           0
146                San Marino        55           0
82                Isle of Man        57           0
147     Sao Tome and Principe        77           0

Bottom 10 countries by fatalities in 2025:
                   COUNTRY  MENTIONS  FATALITIES
1                  Albania     11062           0
3           American Samoa        91           0
4                  Andorra       331           0
10               Australia    287236           0
13                 Bahamas      3151           0
14                 Bahrain      1159           0
20                 Bermuda       824           0
17                 Belgium     22260           0
25  British Virgin Islands        48           0
22  Bosnia and Herzegovina      3298           0

In [63]:
# Save the merged dataset to a new CSV file
output_path = "../data/processed/scatter_plot.csv"
merged_df.to_csv(output_path, index=False)
print(f"Merged dataset saved to {output_path}")

Merged dataset saved to ../data/processed/scatter_plot.csv